irc:
  server: "irc.oftc.net:6667"
  channel: "#rpi"
  nickname: "rpislacker"

slack:
  webhook_url: "https://hooks.slack.com/services/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"
  listen_address: ":3000"  # The address and port to listen for Slack webhooks
  api_token: "xoxb-446402428915-8099589241395-T4FyzpzVDVy1US0GqglS0fKN"  # Bot User OAuth Token from Slack App settings
  ignore_bots: true       # Ignore all bot messages
  ignore_users: []        # List of Slack user IDs to ignore, e.g. ["U1234567890"]
